# Generated by Django 5.0.1 on 2024-02-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id_category', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id_purchase', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase', models.TextField()),
                ('price', models.IntegerField()),
                ('purchase_note', models.TextField(null=True)),
                ('date', models.IntegerField()),
                ('order_status', models.TextField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id_photo', models.IntegerField(primary_key=True, serialize=False)),
                ('id_product', models.CharField(verbose_name=200)),
                ('nazv_product', models.CharField(verbose_name=300)),
                ('ph_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Фотографии',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='product_information',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(verbose_name=200)),
                ('category_id', models.IntegerField(null=True)),
                ('weight', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('structure_goods', models.TextField(null=True)),
                ('possibleboundaries', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Информация о товарах',
                'verbose_name_plural': 'Информация о товарах',
            },
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id_sale', models.IntegerField(primary_key=True, serialize=False)),
                ('name_sale', models.CharField(verbose_name=200)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(null=True)),
                ('purchase_price', models.IntegerField(null=True)),
                ('provider', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Цены товаров',
                'verbose_name_plural': 'Цены товаров',
            },
        ),
    ]
