# Generated by Django 5.0.1 on 2024-02-16 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('note', models.TextField(blank='None', null=True)),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='productinformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150, verbose_name='Имя продукта')),
                ('weight', models.TextField(blank='None', null=True)),
                ('description', models.TextField(blank='None', null=True)),
                ('structure_goods', models.TextField(blank='None', null=True)),
                ('possible_boundaries', models.TextField(blank='None', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories')),
            ],
            options={
                'verbose_name_plural': 'Информация о товарах',
            },
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id_sale', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(blank='None', null=True)),
                ('purchase_price', models.IntegerField(blank='None', null=True)),
                ('provider', models.TextField(blank='None', null=True)),
                ('note', models.TextField(blank='None', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.productinformation')),
            ],
            options={
                'verbose_name_plural': 'Цена товаров',
            },
        ),
    ]
