# Generated by Django 5.0.1 on 2024-02-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_photo', models.CharField(max_length=150)),
                ('id_product', models.CharField(verbose_name=200)),
                ('imagep', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
