# Generated by Django 5.0.1 on 2024-02-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productinformation_image_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinformation',
            name='image_product2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
