# Generated by Django 5.0.1 on 2024-02-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productinformation_image_product2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photo',
        ),
        migrations.RemoveField(
            model_name='productinformation',
            name='possible_boundaries',
        ),
        migrations.RemoveField(
            model_name='productinformation',
            name='structure_goods',
        ),
        migrations.RemoveField(
            model_name='productinformation',
            name='weight',
        ),
        migrations.DeleteModel(
            name='sale',
        ),
    ]
