# Generated by Django 5.0.1 on 2024-01-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compcena',
            fields=[
                ('id_cena', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_price', models.IntegerField()),
                ('price_for_sale', models.IntegerField()),
                ('date_of_purchase', models.DateField()),
                ('info', models.TextField(default=0)),
                ('info2', models.IntegerField(default=0)),
            ],
        ),
    ]
